runtime: python39

env: standard

service: django-app-deploy

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "gcp.settings"

entrypoint: gunicorn -b :$8080 gcp.wsgi

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

handers:
  - url: /static
    static_dir: static/

  - url: /media
    static_dir: media/

  - url: /.*
    script: auto